[env:seeed_xiao_nrf52840]
platform = https://github.com/Seeed-Studio/platform-seeedboards.git
board = seeed-xiao-afruitnrf52-nrf52840
framework = arduino
monitor_speed = 115200
lib_deps =
  adafruit/Adafruit GFX Library
  adafruit/Adafruit SH110X
  adafruit/Adafruit SSD1306
  bblanchon/ArduinoJson @ ^7.0.0
  adafruit/Adafruit MPU6050
  adafruit/Adafruit BMP085 Library
  adafruit/Adafruit Unified Sensor
